# TODO: Also create a GitOpsCluster.apps.open-cluster-management.io
{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- if not .hostedArgoSites }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .name }}-clustergroup-policy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .name }}-clustergroup-config
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: {{ $.Values.global.pattern }}-{{ .name }}
                  namespace: openshift-gitops
                  finalizers:
                  - resources-finalizer.argocd.argoproj.io/foreground
                spec:
                  project: default
                  {{- if $.Values.global.multiSourceSupport }}
                  sources:
                    - repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
                      targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
                      ref: patternref
                    - repoURL: {{ $.Values.global.multiSourceRepoUrl }}
                      targetRevision: {{ $.Values.global.multiSourceTargetRevision }}
                      chart: clustergroup
                      helm:
                        ignoreMissingValueFiles: true
                        values: |
                          extraParametersNested:
                          {{- range $k, $v := $.Values.extraParametersNested }}
                            {{ $k }}: {{ printf "%s" $v | quote }}
                          {{- end }}
                        valueFiles:
                        {{- include "acm.app.policies.multisourcevaluefiles" . | nindent 24 }}
                        {{- range $valueFile := .extraValueFiles }}
                        - {{ $valueFile | quote }}
                        {{- end }}
                        parameters:
                        {{- include "acm.app.policies.helmparameters" $ | nindent 24 }}
                        - name: clusterGroup.name
                          value: {{ $group.name }}
                        {{- range $k, $v := $.Values.extraParametersNested }}
                        - name: {{ $k }}
                          value: {{ printf "%s" $v | quote }}
                        {{- end }}
                       {{- range .helmOverrides }}
                        - name: {{ .name }}
                          value: {{ .value | quote }}
                       {{- end }}
                       {{- if .fileParameters }}
                        fileParameters:
                        {{- range .fileParameters }}
                        - name: {{ .name }}
                          path: {{ .path }}
                        {{- end }}
                       {{- end }}

                  {{- else }}
                  source:
                    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
                    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
                    path: {{ default "common/clustergroup" .path }}
                    helm:
                      ignoreMissingValueFiles: true
                      values: |
                        extraParametersNested:
                        {{- range $k, $v := $.Values.extraParametersNested }}
                          {{ $k }}: {{ printf "%s" $v | quote }}
                        {{- end }}
                      valueFiles:
                      {{- include "acm.app.policies.valuefiles" . | nindent 22 }}
                      {{- range $valueFile := .extraValueFiles }}
                      - {{ $valueFile | quote }}
                      {{- end }}
                      parameters:
                      {{- include "acm.app.policies.helmparameters" $ | nindent 22 }}
                      - name: clusterGroup.name
                        value: {{ $group.name }}
                      {{- range $k, $v := $.Values.extraParametersNested }}
                      - name: {{ $k }}
                        value: {{ printf "%s" $v | quote }}
                      {{- end }}
                     {{- range .helmOverrides }}
                      - name: {{ .name }}
                        value: {{ .value | quote }}
                     {{- end }}
                     {{- if .fileParameters }}
                      fileParameters:
                      {{- range .fileParameters }}
                      - name: {{ .name }}
                        path: {{ .path }}
                      {{- end }}
                     {{- end }}
                  {{- end }}{{/* if $.Values.global.multiSourceSupport */}}
                  destination:
                    server: https://kubernetes.default.svc
                    namespace: {{ $.Values.global.pattern }}-{{ .name }}
                  syncPolicy:
                    automated:
                      prune: false
                      selfHeal: true
                    retry:
                      limit: {{ default 20 $.Values.global.options.applicationRetryLimit }}
                  ignoreDifferences:
                  - group: apps
                    kind: Deployment
                    jsonPointers:
                    - /spec/replicas
                  - group: route.openshift.io
                    kind: Route
                    jsonPointers:
                    - /status
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .name }}-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: {{ .name }}-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: {{ .name }}-clustergroup-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ .name }}-placement
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  {{- if .clusterSelector }}
  clusterSelector: {{ .clusterSelector | toPrettyJson }}
  {{- else if (not $group.acmlabels) }}
  clusterSelector:
    matchLabels:
      clusterGroup: {{ $group.name }}
  {{- else if eq (len $group.acmlabels) 0 }}
  clusterSelector:
    matchLabels:
      clusterGroup: {{ $group.name }}
  {{- else }}
  clusterSelector:
    matchLabels:
    {{- range .acmlabels }}
      {{ .name }}: {{ .value }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
