{{- if eq .Values.global.db.type "EDB" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edb-operator-pull-secret
  namespace: openshift-operators
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: postgresql-operator-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"docker.enterprisedb.com":{"username":"k8s","password":"{{ `{{ .token }}` }}","auth":"{{ `{{ printf \"k8s:%s\" .token | b64enc }}` }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.edb.key }}
        property: token
{{- end }}
