---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: huggingface-secret
spec:
  refreshInterval: 2m0s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  dataFrom:
  - extract:
      key: {{ .Values.hfmodel.key }}
