main:
  gitops:
    channel: "gitops-1.12"

global:
  extraValueFiles: []
  pattern: none
  repoURL: none
  targetRevision: main
  options:
    applicationRetryLimit: 20
  secretStore:
    backend: "vault"

clusterGroup:
  subscriptions:
    acm:
      source: redhat-operators
  managedClusterGroups:
#    testRegion:
#      name: region-one
#      clusterPools:
#        testPool:
#          name: spoke
#          openshiftVersion: 4.10.18
#          baseDomain: blueprints.rhecoeng.com
#          platform:
#            aws:
#              region: ap-southeast-2
#          clusters:
#          - spoke1
#      labels:
#      - name: clusterGroup
#        value: region-one
#    testRegionTwo:
#      name: region-two
#      clusterDeployments:
#        myFirstCluster:
#          name: mcluster1
#          openshiftVersion: 4.10.18
#          baseDomain: blueprints.rhecoeng.com
#          platform:
#            azure:
#              baseDomainResourceGroupName: dojo-dns-zones
#              region: eastus
#      labels:
#        - name: clusterGroup
#          value: region-two

acm:
  # Just used for IIB testing, drives the source and channel for the MCE
  # subscription triggered by ACM
  mce_operator:
    source: redhat-operators
    channel: null



secretStore:
  name: vault-backend
  kind: ClusterSecretStore
