---
name: Split into chart repo branches

on:
  workflow_call:
    inputs:
      chart_name:
        required: true
        type: string
      target_repository:
        required: true
        type: string

jobs:
  split_chart:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CHARTS_REPOS_TOKEN }}

      - name: Run git subtree split and push
        env:
          GITHUB_TOKEN: ${{ secrets.CHARTS_REPOS_TOKEN }}
        run: |
          set -e
          N="${{ inputs.chart_name }}"
          B="${N}-main-single-chart"
          GITIMG="quay.io/hybridcloudpatterns/gitsubtree-container:2.40.1"
          sudo apt-get update -y && sudo apt-get install -y podman
          echo "Running subtree split for ${B}"
          podman pull "${GITIMG}"
          git push origin -d "${B}" || /bin/true
          # Git subtree got broken on recent versions of git hence this container
          podman run --net=host --rm -t -v .:/git "${GITIMG}" subtree split -P "${N}" -b "${B}"
          #git clone https://validatedpatterns:${GITHUB_TOKEN}@github.com/validatedpatterns/common.git -b "acm-main-single-chart" --single-branch
          git push --force https://validatedpatterns:"${GITHUB_TOKEN}"@github.com/${{ inputs.target_repository }}.git "${B}:main"
