{{- if eq .Values.global.db.type "MSSQL" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-pull-secret-tpl
data:
  .dockerconfigjson: |-
    {"auths":{"{{ .Values.image.registry }}":{"username":"{{ `{{ .dockeruser }}` }}","password":"{{ `{{ .dockerpass }}` }}","auth":"{{ `{{ .dockerauth }}` }}"}}}
{{- end }}
