{{- if eq .Values.global.db.type "MSSQL" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mssql-pull-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: mssql-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          name: mssql-pull-secret-tpl
          items:
          - key: .dockerconfigjson
            templateAs: Values
  data:
  - secretKey: dockerauth
    remoteRef:
      key: {{ .Values.secretStore.mssqlSecretKey }}
      property: "dockerauth"
  - secretKey: dockeruser
    remoteRef:
      key: {{ .Values.secretStore.mssqlSecretKey }}
      property: "dockeruser"
  - secretKey: dockerpass
    remoteRef:
      key: {{ .Values.secretStore.mssqlSecretKey }}
      property: "dockerpass"
{{- end }}
