{{- if eq .Values.global.db.type "MSSQL" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  accessModes:
  - {{ .Values.pvc.mssqldataaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.mssqldbsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-userdb
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  accessModes:
  - {{ .Values.pvc.userdbaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.userdbsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-log
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  accessModes:
   - {{ .Values.pvc.userlogaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.userlogsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-temp
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  accessModes:
   - {{ .Values.pvc.tempdbaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.tempsize}}
{{- end }}
