apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ai-llm-grafana
spec:
  config:
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    auth.anonymous:
      enabled: "true"
    log:
      level: error
      mode: console
    log.frontend:
      enabled: "true"
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  ingress:
    enabled: true
    path: /
    pathType: Prefix
