apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack-server
spec:
  selector:
    matchLabels:
      app: redis-stack-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stack-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis-stack-server
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          image: quay.io/ecosystem-appeng/redis-stack-server:7.2.0-v9
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: db
          volumeMounts:
            - name: db
              mountPath: /data
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-redis-stack-server
