{{/* If the backend is not set at all we default to "vault". See https://www.github.com/helm/helm/issues/3308
     why we avoid using the default function */}}
{{- if or (eq .Values.global.secretStore.backend "vault") (not (hasKey .Values.global.secretStore "backend")) }}
{{- if not (eq .Values.enabled "plumbing") }}
{{- if $.Values.clusterGroup.isHubCluster }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: unsealvault-cronjob
  namespace: {{ $.Values.clusterGroup.imperative.namespace}}
spec:
  schedule: {{ $.Values.clusterGroup.imperative.insecureUnsealVaultInsideClusterSchedule | quote }}
  # if previous Job is still running, skip execution of a new Job
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.clusterGroup.imperative.activeDeadlineSeconds }}
      template:
        metadata:
          name: unsealvault-job
        spec:
          serviceAccountName: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
          initContainers:
            # git init happens in /git/repo so that we can set the folder to 0770 permissions
            # reason for that is ansible refuses to create temporary folders in there
            {{- include  "imperative.initcontainers.fetch-ca" . | indent 12 }}
            {{- include  "imperative.initcontainers.gitinit-ca" . | indent 12 }}
            - name: unseal-playbook
              image: {{ $.Values.clusterGroup.imperative.image }}
              imagePullPolicy: {{ $.Values.clusterGroup.imperative.imagePullPolicy }}
              env:
                - name: HOME
                  value: /git/home
              workingDir: /git/repo
              # We have a default timeout of 600s for each playbook. Can be overridden
              # on a per-job basis
              command:
                - timeout
                - {{ .timeout | default "600" | quote }}
                - ansible-playbook
                {{- if $.Values.clusterGroup.imperative.verbosity }}
                - {{ $.Values.clusterGroup.imperative.verbosity }}
                {{- end }}
                - -e
                - "@/values/values.yaml"
                - -t
                - 'vault_init,vault_unseal,vault_secrets_init,vault_spokes_init'
                - "common/ansible/playbooks/vault/vault.yaml"
              volumeMounts:
                {{- include "imperative.volumemounts_ca" . | indent 16 }}
          containers:
          {{- include "imperative.containers.done" . | indent 12 }}
          volumes:
          {{- include "imperative.volumes_ca" . | indent 12 }}
          restartPolicy: Never
{{- end }}
{{- end }}
{{- end }}
