{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- range .clusterPools }}
{{- $poolName := print .name "-" $group.name }}
{{- if .platform.azure }}
---
{{- template "externalsecret.azure.creds" (dict "name" $poolName "context" . "secretStore" $.Values.secretStore) }}
---
{{- template "externalsecret.azure.infra-creds" (dict "name" $poolName "context" . "secretStore" $.Values.secretStore) }}

---
{{- end }}{{- /* if .platform.azure */}}
{{- end }}{{- /* range .clusterPools  */}}

{{- range .clusterDeployments }}
{{- $deploymentName := print .name "-" $group.name }}
{{- if .platform.azure }}
---
{{- template "externalsecret.azure.creds" (dict "name" $deploymentName "context" . "secretStore" $.Values.secretStore "namespaced" true) }}
---
{{- template "externalsecret.azure.infra-creds" (dict "name" $deploymentName "context" . "secretStore" $.Values.secretStore "namespaced" true) }}


{{- end }}{{- /* if .platform.azure */}}
{{- end }}{{- /* range .clusterPools  */}}

{{- end }}{{- /* range .Values.clusterGroup.managedClusterGroups  */}}

{{- define "externalsecret.azure.creds" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-creds
  {{- if .namespaced }}
  namespace: {{ .name }}
  {{- end }}
spec:
  data:
  - secretKey: azureOsServicePrincipal
    remoteRef:
      key: {{ default "secret/data/hub/azureOsServicePrincipal" .context.azureKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ .name }}-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}
{{- end }}

{{- define "externalsecret.azure.infra-creds"}}
# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-infra-creds
  {{- if .namespaced }}
  namespace: {{ .name }}
  {{- end }}
spec:
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .context.pullSecretKeyPath }}
      property: content
  - secretKey: sshPublicKey
    remoteRef:
      key: {{ default "secret/data/hub/publickey" .context.sshPublicKeyPath }}
      property: content
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .context.sshPrivateKeyPath }}
      property: content
  - secretKey: azureOsServicePrincipal
    remoteRef:
      key: {{ default "secret/data/hub/azureOsServicePrincipal" .context.azureKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ .name }}-infra-creds
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      data:
        cloudName: AzurePublicCloud
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}
        baseDomain: "{{ .context.baseDomain }}"
        baseDomainResourceGroupName: "{{ .context.platform.azure.baseDomainResourceGroupName | toString }}"
        pullSecret: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
        ssh-publickey: |-
          {{ "{{ .sshPublicKey | toString }}" }}
        httpProxy: ""
        httpsProxy: ""
        noProxy: ""
        additionalTrustBundle: ""
{{- end }}
