{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}

{{- range .clusterPools }}
{{- $poolName := print .name "-" $group.name }}
---
{{- template "secret.install-config" (dict "name" $poolName "context" .) }}
---
{{- template "externalsecret.pull-secret" (dict "name" $poolName "context" . "secretStore" $.Values.secretStore) }}
---
{{- template "externalsecret.ssh.private.key" (dict "name" $poolName "context" . "secretStore" $.Values.secretStore) }}
{{- end }}{{- /* range .clusterPools */}}

{{- range .clusterDeployments }}
{{- $deploymentName := print .name "-" $group.name }}
---
{{- template "secret.install-config" (dict "name" $deploymentName "context" . "namespaced" true) }}
---
{{- template "externalsecret.pull-secret" (dict "name" $deploymentName "context" . "secretStore" $.Values.secretStore "namespaced" true) }}
---
{{- template "externalsecret.ssh.private.key" (dict "name" $deploymentName "context" . "secretStore" $.Values.secretStore "namespaced" true) }}
{{- end }}{{- /* range .clusterDeplyments */}}

{{- end }}{{- /* range .Values.clusterGroup.managedClusterGroups */}}

{{- define "secret.install-config"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-install-config
  {{- if .namespaced }}
  namespace: {{ .name }}
  {{- end }}
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.install-config" .context | b64enc }}
type: Opaque
{{- end }}

{{- define "externalsecret.pull-secret" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-pull-secret
  {{- if .namespaced }}
  namespace: {{ .name }}
  {{- end }}
spec:
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: {{ default "secret/data/hub/openshiftPullSecret" .context.pullSecretKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ .name }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}
{{- end }}


{{- define "externalsecret.ssh.private.key" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-ssh-private-key
  {{- if .namespaced }}
  namespace: {{ .name }}
  {{- end }}
spec:
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: {{ default "secret/data/hub/privatekey" .context.sshPrivateKeyPath }}
      property: content
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ .name }}-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ "{{ .sshPrivateKey | toString }}" }}
{{- end }}
