global:
  extraValueFiles: []

main:
  git:
    # Uncommenting this will set the `originRepo` with the below value
    # when `originRepo` is set, an in-cluster gitea will automatically be spawned.
    # In this case `originRepo` will point to the upstream repository and `targetRepo`
    # will point to the internal in-cluster gitea mirror
    # repoUpstreamURL: https://github.com/validatedpatterns/multicloud-gitops
    repoURL: https://github.com/pattern-clone/mypattern
    revision: main

  gitops:
    channel: "gitops-1.12"
    operatorSource: redhat-operators

  multiSourceConfig:
    enabled: false

  # String to enable certain experimental capabilities in the operator and the
  # framework. Not needed unless you know exactly what you're doing.
  experimentalCapabilities: ""

  patternsOperator:
    channel: fast
    source: community-operators
    installPlanApproval: Automatic
    sourceNamespace: openshift-marketplace
    startingCSV: null

  clusterGroupName: default

  # If you are using a private repository define the secret where
  # credentials to access the private repository are
  # tokenSecret:
  # tokenSecretNamespace:
