global:
  db:
    type: MSSQL
  storageClass: managed-csi

clusterGroup:
  imperative:
    jobs:
      - name: create-gpu-machineset
        playbook: ansible/playbooks/create-gpu-machineset-azure.yaml
    clusterRoleYaml:
      - apiGroups:
          - "*"
        resources:
          - machinesets
          - persistentvolumeclaims
          - datavolumes
          - dataimportcrons
          - datasources
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch
