{
 "title": "MODEL FEEDBACK/RATING",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "ModelID", "query": { "query": "label_values(model_id)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$ModelID - RATINGS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "ModelID",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"$namespace\", model_id=\"${ModelID:raw}\"}) by (stars)"
    }
   ]
  },
  {
   "title": "$ModelID - RATINGS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"$namespace\", model_id=\"${ModelID:raw}\"}) by (stars)"
    }
   ]
  },
  {
   "title": "$ModelID - AVERAGE RATING",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "repeat": "ModelID",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"${ModelID:raw}\"} or on() vector(0))* 1) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 2) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 3) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 4) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 5)) \n/\n(sum(feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"${ModelID:raw}\"} or on() vector(0)))",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "$ModelID - AVERAGE RATING",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"${ModelID:raw}\"} or on() vector(0))* 1) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 2) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 3) + sum((feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 4) +\nsum((feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"${ModelID:raw}\"} or on() vector(0)) * 5)) \n/\n(sum(feedback_stars_total{namespace=\"$namespace\", stars=\"1\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"2\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"3\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"4\", model_id=\"${ModelID:raw}\"} or on() vector(0)) + sum(feedback_stars_total{namespace=\"$namespace\", stars=\"5\", model_id=\"${ModelID:raw}\"} or on() vector(0)))",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "$ModelID - MODEL USAGE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "repeat": "ModelID",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_usage_total{model_id=\"${ModelID:raw}\",namespace=\"$namespace\"}",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "$ModelID - MODEL USAGE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_usage_total{model_id=\"${ModelID:raw}\",namespace=\"$namespace\"}",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "RESPONSE TIME  UI -> INFERENCE SERVER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "request_duration_seconds{namespace=\"${namespace}\"}",
     "legendFormat": "{{model_id}}"
    }
   ]
  }
 ]
}