# This playbook will watch for pending install plans of managed operators
# if they are in Manual and there's a startingCSV that must be installed
---
- name: InstallPlan Auto-Approver
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
  - name: Get all installPlans from OpenShift
    kubernetes.core.k8s_info:
      api_version: operators.coreos.com/v1alpha1
      kind: InstallPlan
    register: installplans

  - name: Get required CSVs from clusterGroup data
    ansible.builtin.set_fact:
      expected_csv: "{{ expected_csv | default([]) + [item.csv] }}"
    when: item.csv | default(false) and
          ((item.installPlanApproval | default("") == "Manual") or
          (item.installPlanApproval | default("") == "" and global.options.installPlanApproval | default("") == "Manual"))
    with_items: "{{ clusterGroup.subscriptions.values() }}"

  # TODO: loop over clusterGroup.subscriptions instead of installplans
  #       to allow certain control on the order of approvals
  # IDEA: allow adding a per-installplan delay after the approval before
  #       moving forward to the next one
  - name: Approve the missing installPlans
    kubernetes.core.k8s_json_patch:
      api_version: operators.coreos.com/v1alpha1
      kind: InstallPlan
      name: "{{ item.metadata.name }}"
      namespace: "{{ item.metadata.namespace }}"
      patch:
      - op: replace
        path: /spec/approved
        value: true
    when: (item.spec.clusterServiceVersionNames | intersect(expected_csv | default([]))) | length > 0
    loop: "{{ installplans.resources }}"
