{{- if and (eq .Values.global.db.type "PGVECTOR") .Values.secret.create }}
kind: Secret
apiVersion: v1
metadata:
  name: vectordb-app
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
data:
  username: {{ .Values.secret.user | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
  host: {{ default (include "pgvector.fullname" .) .Values.secret.host | b64enc | quote }}
  port: {{ .Values.secret.port | b64enc | quote }}
  dbname: {{ .Values.secret.dbname | b64enc | quote }}
type: Opaque
{{- end }}
