{{- if eq .Values.global.db.type "PGVECTOR" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: pgvector-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: vectordb-app
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        dbname: "{{ `{{ .dbname }}` }}"
        host: {{ include "pgvector.fullname" . }}
        port: "{{ .Values.service.port }}"
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: password
  - secretKey: dbname
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: dbname
{{- end }}
